Recalculate average scores for games
juanmbellini/PowerUp pull request #142
Opened 2017-12-09 22:34 UTC by lipusal

2017-12-09 23:41 UTC, juanmbellini reviewed
Me parece que tenés mal el nombre de la review. Si no leo mal dice 20171207... Hoy es 9 de diciembre...

2017-12-10 00:19 UTC, lipusal commented
Whoops, tenés razón, me mezclé porque eran las 7 de la noche. Lo cambio.

### TODO
- [ ] Change migration date

2017-12-10 01:38 UTC, juanmbellini commented
👍 
Cambialo cuando puedas, así no volvemos a tener problemas con flyway en pawserver

2017-12-10 01:44 UTC, juanmbellini requested changes
Cambiar nombre de la migration

2017-12-10 01:51 UTC, juanmbellini approved these changes

2017-12-10 03:46 UTC, merged