Improve code readability
juanmbellini/PowerUp pull request #34
Opened 2017-09-28 05:11 UTC by juanmbellini

Closes #30

2017-09-28 22:58 UTC, lipusal requested changes
Algunos comments generales pero otros que sí me parece que habría que revisar

2017-09-28 22:58 UTC, lipusal commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/ReviewJerseyController.java
> +                .header("Access-Control-Allow-Methods", "PUT,DELETE,OPTIONS,POST,GET") // TODO: PUT and DELETE are not supported methods for /reviews
Por qué no? Deberíamos permitirlos, las reviews tienen los botones de edit y delete

2017-09-28 22:58 UTC, lipusal commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/ReviewJerseyController.java
> +                .addParameter("id", reviewId, id -> id <= 0));
Me parece más claro el código que estaba antes, y de usar `reviewId`, aunque el segundo no es tan importante

2017-09-28 22:58 UTC, lipusal commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/UserJerseyController.java
> +
Me parece extremadamente verborrágico y al pedo, lo anterior era más conciso e iba al grano (chequear que algo no sea null)

2017-09-28 22:58 UTC, lipusal commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/UserJerseyController.java
> +                .addParameter("id", userId, id -> id <= 0));
Ídem acá y en todos los demás lugares

2017-09-28 22:58 UTC, lipusal commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/UserJerseyController.java
> +                .addParameter("gameId", gameId, id -> id <= 0));
Esto sí me parece piola

2017-09-29 02:29 UTC, juanmbellini commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/ReviewJerseyController.java
> +                .header("Access-Control-Allow-Methods", "PUT,DELETE,OPTIONS,POST,GET") // TODO: PUT and DELETE are not supported methods for /reviews
Sisi, pero el endpoint para eso es ```/reviews/:id```, no ```/reviews```

2017-09-29 02:31 UTC, juanmbellini commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/ReviewJerseyController.java
> +                .addParameter("id", reviewId, id -> id <= 0));
Claro, pero al documentación dice ```/reviews/:id``` para el resto de los endpoints. Sino tengo que cambiar todos los demás.
Además, por otro lado, estamos dentro de "reviews" por lo que, teniendo solo ":id", se sobreentiende que es el "id del review".

2017-09-29 02:33 UTC, juanmbellini commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/UserJerseyController.java
> +
Lo hice para mantener consistencia. El método ```JerseyControllerHelper#checkParameters``` sirve para verificar parámetros todos juntos (en caso de que te equivocaste en más de uno, te avisa por todos). Si uso de la manera de antes, te puedo avisar de a uno.
Además, de esta manera, centralizo la lógica de cómo resolver este problema (qué hago y cómo lo hago, y cómo le doy aviso al cliente).

2017-09-29 02:34 UTC, juanmbellini commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/UserJerseyController.java
> +                .addParameter("id", userId, id -> id <= 0));
En este caso, estoy chequeando los parámetros ```pageSize``` y ```pageNumber```, además de ```id```.

2017-09-29 02:35 UTC, juanmbellini commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/UserJerseyController.java
> +                .addParameter("gameId", gameId, id -> id <= 0));
👍

2017-09-30 02:04 UTC, lipusal commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/ReviewJerseyController.java
> +                .addParameter("id", reviewId, id -> id <= 0));
Entiendo lo de `id`, me parecía poco claro la manera nueva de chequear errores. Claramente ya es demasiado tarde para que lo reviertas así que ya fue

2017-09-30 02:07 UTC, lipusal commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/UserJerseyController.java
> +
Por lo de centralizar el comportamiento te lo permito, pero sino preferiría el anterior porque de todas maneras acá estás chequeando un solo valor. Está bien lo de centralizar comportamiento igual, pero quedan re anti-intuitiva estas líneas (hay un `Objects::isNull` en vez de `Objects::isNotNull`, a rápida vista parece que esto está chequeando que el parámetro **sí** sea NULL). No me sorprendería que recibamos críticas por esto, pero dejalo

2017-09-30 02:09 UTC, lipusal approved these changes

2017-09-30 02:24 UTC, juanmbellini commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/ReviewJerseyController.java
> +                .addParameter("id", reviewId, id -> id <= 0));
👍

2017-09-30 02:26 UTC, juanmbellini commented on paw-webapp/webapp/src/main/java/ar/edu/itba/paw/webapp/controller/UserJerseyController.java
> +
👍

2017-09-30 02:26 UTC, merged