Comment and replies count
juanmbellini/PowerUp pull request #8
Opened 2017-07-22 03:25 UTC by juanmbellini

2017-07-22 17:20 UTC, lipusal requested changes
El único change obligatorio es una boludez, el de copy-pasta.  Lo del wrapper me gustaría que me lo expliques, si no queda otra por ahora mergeemoslo y después vemos si se puede cambiar el approach

2017-07-22 17:20 UTC, lipusal commented on paw-webapp/interfaces/src/main/java/ar/edu/itba/paw/webapp/interfaces/ThreadService.java
> +import ar.edu.itba.paw.webapp.model_wrappers.CommentableAndLikeableWrapper;
Después explicá por el grupo porqué usamos un wrapper así, esto grita que deberían ser dos cosas aparte.  Me parece muy raro.

2017-07-22 17:20 UTC, lipusal commented on paw-webapp/persistence/src/main/java/ar/edu/itba/paw/webapp/persistence/CommentHibernateDao.java
> +        // The likes list holds Object arrays with two elements each: entity id and likes count
Copy pasta: holds Object arrays with two elements each: entity id and ~likes~ reply count

2017-07-22 21:50 UTC, juanmbellini commented on paw-webapp/persistence/src/main/java/ar/edu/itba/paw/webapp/persistence/CommentHibernateDao.java
> +        // The likes list holds Object arrays with two elements each: entity id and likes count
Listo

2017-07-25 23:47 UTC, lipusal approved these changes

2017-07-25 23:56 UTC, merged